"""
Article Formatter — Template-based article rendering.

Provides tools for rendering articles in platform-specific formats
using Jinja2-style templates (without the Jinja2 dependency).
"""

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any


class ArticleFormatter:
    """Format articles for different platforms using templates."""

    def __init__(self, template_dir: str | None = None):
        self.template_dir = template_dir or os.path.join(
            os.path.dirname(os.path.dirname(__file__)), "templates"
        )

    def render(self, template_name: str, context: dict[str, Any]) -> str:
        """Render a template with context variables."""
        template_path = os.path.join(self.template_dir, template_name)
        if os.path.exists(template_path):
            with open(template_path, "r", encoding="utf-8") as f:
                template = f.read()
        else:
            template = self._default_template(template_name)

        return self._render_template(template, context)

    def _render_template(self, template: str, context: dict[str, Any]) -> str:
        """Simple template engine with variable substitution and loops."""
        result = template

        # Variable substitution: {{ var }}
        for key, value in context.items():
            if isinstance(value, str):
                result = result.replace(f"{{{{ {key} }}}}", value)
            elif isinstance(value, list):
                placeholder = f"{{{{ {key} }}}}"
                if placeholder in result:
                    rendered = "\n".join(f"- {item}" for item in value)
                    result = result.replace(placeholder, rendered)

        # Remove any unfilled placeholders
        result = re.sub(r"\{\{.*?\}\}", "", result)

        return result

    def _default_template(self, platform: str) -> str:
        """Return a default template if no file exists."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        return f"""---
title: {{ title }}
date: {date_str}
tags: [{{ tags }}]
---

## {{ summary }}

{{ content }}

---

*Generated by Agent Daily Publisher on {date_str}*
"""

    def format_for_platform(self, platform: str, article: dict[str, Any]) -> str:
        """Format an article dict for a specific platform."""
        context = {
            "title": article.get("title", "技术日报"),
            "date": datetime.now().strftime("%Y-%m-%d"),
            "tags": ", ".join(article.get("tags", ["技术"])),
            "summary": article.get("summary", ""),
            "highlights": article.get("highlights", []),
            "content": self._build_content(article, platform),
        }

        template_name = f"{platform}.md.j2"
        return self.render(template_name, context)

    def _build_content(self, article: dict[str, Any], platform: str) -> str:
        """Build the main content body from article data."""
        parts = []

        # Summary section
        if article.get("summary"):
            parts.append(f"## 📌 今日概述\n\n{article['summary']}")

        # Highlights
        highlights = article.get("highlights", [])
        if highlights:
            parts.append("## 🔧 问题和方案\n")
            for h in highlights:
                parts.append(f"### {h.get('title', 'Issue')}")
                if h.get("context"):
                    parts.append(f"**背景**：{h['context']}")
                if h.get("root_cause"):
                    parts.append(f"**根因**：{h['root_cause']}")
                if h.get("solution"):
                    parts.append(f"**方案**：{h['solution']}")
                if h.get("code_snippet") and platform in ("juejin", "devto"):
                    parts.append(f"```\n{h['code_snippet']}\n```")
                parts.append("")

        # Architecture decisions
        decisions = article.get("architecture_decisions", [])
        if decisions:
            parts.append("## 🏗 架构决策\n")
            for d in decisions:
                parts.append(f"- **{d.get('decision', '')}**")
                if d.get("rationale"):
                    parts.append(f"  - 理由：{d['rationale']}")
                parts.append("")

        # Insights
        insights = article.get("key_insights", [])
        if insights:
            parts.append("## 💡 关键收获\n")
            for insight in insights:
                parts.append(f"- {insight}")

        return "\n".join(parts)


def save_article(article: dict[str, Any], output_dir: str | None = None) -> str:
    """Save article to a markdown file. Returns file path."""
    if output_dir is None:
        output_dir = os.path.join(
            os.path.dirname(os.path.dirname(__file__)), "data", "articles"
        )
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    date_str = datetime.now().strftime("%Y-%m-%d")
    title_slug = article.get("title", "article").replace(" ", "-")[:30]
    filename = f"{date_str}_{title_slug}.md"
    filepath = os.path.join(output_dir, filename)

    content = article.get("content", article.get("raw_content", ""))
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath
